INSERT INTO business_partners
SELECT * FROM json_to_recordset('[
  {
    "bpn": "CAXLZJVJEBYWYYZZ",
    "parent": null,
    "accountGroup": "OEM",
    "name1": "Bayerische Motoren Werke Aktiengesellschaft",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Tucker",
    "postalCode": "61828",
    "street1": "Ridgefield",
    "street2": null,
    "street3": null,
    "houseNumber": "17",
    "taxNumber1": "DE084342972",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE084342972",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXSPGQORIGHFAZZ",
    "parent": "CAXLZJVJEBYWYYZZ",
    "accountGroup": "OEM Plant",
    "name1": "BMW Plant Munich",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Austell",
    "postalCode": "16679",
    "street1": "Shaliman",
    "street2": null,
    "street3": null,
    "houseNumber": "31",
    "taxNumber1": "DE470914600",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE470914600",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXSWPFTJQEVZNZZ",
    "parent": "CAXLZJVJEBYWYYZZ",
    "accountGroup": "OEM Plant",
    "name1": "BMW Plant Dingolfing",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Bronwood",
    "postalCode": "56551",
    "street1": "Village",
    "street2": null,
    "street3": null,
    "houseNumber": "49",
    "taxNumber1": "DE539212588",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE539212588",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXSZJVJEBYWYYZZ",
    "parent": "CAXLZJVJEBYWYYZZ",
    "accountGroup": "OEM Plant",
    "name1": "BMW Plant Leipzig",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Lincolnton",
    "postalCode": "40784",
    "street1": "Putnam",
    "street2": null,
    "street3": null,
    "houseNumber": "17",
    "taxNumber1": "DE976557336",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE976557336",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXLXCLMNDAAWEZZ",
    "parent": null,
    "accountGroup": "OEM",
    "name1": "Daimler AG",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Rome",
    "postalCode": "11169",
    "street1": "Pinewood",
    "street2": null,
    "street3": null,
    "houseNumber": "90",
    "taxNumber1": "DE794533137",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE794533137",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXLTHAJNAHZXGZZ",
    "parent": null,
    "accountGroup": "Supplier",
    "name1": "ZF Friedrichshafen AG",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Amboy",
    "postalCode": "00587",
    "street1": "Darlington",
    "street2": null,
    "street3": null,
    "houseNumber": "47",
    "taxNumber1": "DE596524704",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE596524704",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXLXZZDURIFEUZZ",
    "parent": null,
    "accountGroup": "Supplier",
    "name1": "Robert Bosch GmbH",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Ochlocknee",
    "postalCode": "56341",
    "street1": "Moxadarla",
    "street2": null,
    "street3": null,
    "houseNumber": "39",
    "taxNumber1": "DE229486404",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE229486404",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXLBRHHQAJAIOZZ",
    "parent": null,
    "accountGroup": "Supplier",
    "name1": "BASF",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Thomaston",
    "postalCode": "57102",
    "street1": "Mccarley",
    "street2": null,
    "street3": null,
    "houseNumber": "74",
    "taxNumber1": "DE163944393",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE163944393",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXLHNJURNRLPCZZ",
    "parent": null,
    "accountGroup": "Supplier",
    "name1": "Henkel",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Dalton",
    "postalCode": "05725",
    "street1": "Crawford",
    "street2": null,
    "street3": null,
    "houseNumber": "50",
    "taxNumber1": "DE751071043",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE751071043",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXLJXFARPBQZQZZ",
    "parent": null,
    "accountGroup": "Supplier",
    "name1": "Kaputt GmbH",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Saint George",
    "postalCode": "26393",
    "street1": "Fritter",
    "street2": null,
    "street3": null,
    "houseNumber": "01",
    "taxNumber1": "DE504596517",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE504596517",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXLAPHGVJJFHZZZ",
    "parent": null,
    "accountGroup": "Technology",
    "name1": "SAP AG",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Enigma",
    "postalCode": "74464",
    "street1": "Parkwood",
    "street2": null,
    "street3": null,
    "houseNumber": "89",
    "taxNumber1": "DE413615188",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE413615188",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXLCPOZSGFCTJZZ",
    "parent": null,
    "accountGroup": "Technology",
    "name1": "Microsoft",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Cogdell",
    "postalCode": "61522",
    "street1": "Davis",
    "street2": null,
    "street3": null,
    "houseNumber": "07",
    "taxNumber1": "DE071273179",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE071273179",
    "vatNumberType": "UST-ID"
  },
  {
    "bpn": "CAXLNDDMHMMNCOZZ",
    "parent": null,
    "accountGroup": "Technology",
    "name1": "T-Systems",
    "name2": null,
    "name3": null,
    "name4": null,
    "addressVersion": "EN",
    "country": "Germany",
    "city": "Mcrae",
    "postalCode": "93174",
    "street1": "Durban",
    "street2": null,
    "street3": null,
    "houseNumber": "15",
    "taxNumber1": "DE471126090",
    "taxNumber1Type": "UST-ID",
    "taxNumber2": null,
    "taxNumber2Type": null,
    "taxNumber3": null,
    "taxNumber3Type": null,
    "taxNumber4": null,
    "taxNumber4Type": null,
    "taxNumber5": null,
    "taxNumber5Type": null,
    "vatNumber": "DE471126090",
    "vatNumberType": "UST-ID"
  }
]') AS (
    bpn VARCHAR(200),
    parent VARCHAR(200),
    accountGroup VARCHAR(200),
    name1 VARCHAR(200),
    name2 VARCHAR(200),
    name3 VARCHAR(200),
    name4 VARCHAR(200),
    addressVersion VARCHAR(200),
    country VARCHAR(200),
    city VARCHAR(200),
    postalCode VARCHAR(200),
    street1 VARCHAR(200),
    street2 VARCHAR(200),
    street3 VARCHAR(200),
    houseNumber VARCHAR(200),
    taxNumber1 VARCHAR(200),
    taxNumber1Type VARCHAR(200),
    taxNumber2 VARCHAR(200),
    taxNumber2Type VARCHAR(200),
    taxNumber3 VARCHAR(200),
    taxNumber3Type VARCHAR(200),
    taxNumber4 VARCHAR(200),
    taxNumber4Type VARCHAR(200),
    taxNumber5 VARCHAR(200),
    taxNumber5Type VARCHAR(200),
    vatNumber VARCHAR(200),
    vatNumberType VARCHAR(200)
);
