@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant "KAPUTT Service" as KaputtService 
participant "KAPUTT Consumer" as KaputtConsumer #efefef
participant "Company A Provider" as CompanyAProvider #efefef
participant "Company A Aspects Service" as AspectsServiceCompanyA 

KaputtService ->  KaputtConsumer: "http://kaputt-consumer/artifacts/<some-id>/data"
KaputtConsumer -> CompanyAProvider: "http://companyA-provider/artifacts/<remote-id>/data/<params>"
CompanyAProvider -> AspectsServiceCompanyA: Get aspect \n"http://companyA-aspects-api/<params>"
CompanyAProvider <-- AspectsServiceCompanyA: AspectData
KaputtConsumer <-- CompanyAProvider: AspectData
KaputtService <-- KaputtConsumer: AspectData
@enduml