apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "clearinghouse.fullname" . }}-certs
  labels:
    {{- include "clearinghouse.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{- ( include "gen.secret" . ) | indent 2 }}
{{ (.Files.Glob "files/*").AsSecrets | indent 2}}