apiVersion: v1
kind: Service
metadata:
  name: {{ include "clearinghouse.fullname" . }}
  labels:
    {{- include "clearinghouse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: clearinghouse
      protocol: TCP
      name: http
  selector:
    {{- include "clearinghouse.selectorLabels" . | nindent 4 }}
