/*
 * Dataspace Connector
 * IDS Connector originally developed by the Fraunhofer ISST
 *
 * OpenAPI spec version: 6.2.0
 * Contact: info@dataspace-connector.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.catenax.semantics.framework.dsc.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * OfferedResourceView
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-08T16:15:16.333286600+02:00[Europe/Berlin]")
public class OfferedResourceView {
  @JsonProperty("creationDate")
  private OffsetDateTime creationDate = null;

  @JsonProperty("modificationDate")
  private OffsetDateTime modificationDate = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("keywords")
  private List<String> keywords = null;

  @JsonProperty("publisher")
  private String publisher = null;

  @JsonProperty("language")
  private String language = null;

  @JsonProperty("license")
  private String license = null;

  @JsonProperty("version")
  private Long version = null;

  @JsonProperty("sovereign")
  private String sovereign = null;

  @JsonProperty("endpointDocumentation")
  private String endpointDocumentation = null;

  /**
   * Gets or Sets paymentModality
   */
  public enum PaymentModalityEnum {
    UNDEFINED("undefined"),
    FIXEDPRICE("fixedPrice"),
    FREE("free"),
    NEGOTIATIONBASIS("negotiationBasis");

    private String value;

    PaymentModalityEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PaymentModalityEnum fromValue(String text) {
      for (PaymentModalityEnum b : PaymentModalityEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("paymentModality")
  private PaymentModalityEnum paymentModality = null;

  @JsonProperty("samples")
  private List<String> samples = null;

  @JsonProperty("additional")
  private Map<String, String> additional = null;

  @JsonProperty("_links")
  private Links _links = null;

  public OfferedResourceView creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @Schema(description = "")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public OfferedResourceView modificationDate(OffsetDateTime modificationDate) {
    this.modificationDate = modificationDate;
    return this;
  }

   /**
   * Get modificationDate
   * @return modificationDate
  **/
  @Schema(description = "")
  public OffsetDateTime getModificationDate() {
    return modificationDate;
  }

  public void setModificationDate(OffsetDateTime modificationDate) {
    this.modificationDate = modificationDate;
  }

  public OfferedResourceView title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public OfferedResourceView description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OfferedResourceView keywords(List<String> keywords) {
    this.keywords = keywords;
    return this;
  }

  public OfferedResourceView addKeywordsItem(String keywordsItem) {
    if (this.keywords == null) {
      this.keywords = new ArrayList<>();
    }
    this.keywords.add(keywordsItem);
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  @Schema(description = "")
  public List<String> getKeywords() {
    return keywords;
  }

  public void setKeywords(List<String> keywords) {
    this.keywords = keywords;
  }

  public OfferedResourceView publisher(String publisher) {
    this.publisher = publisher;
    return this;
  }

   /**
   * Get publisher
   * @return publisher
  **/
  @Schema(description = "")
  public String getPublisher() {
    return publisher;
  }

  public void setPublisher(String publisher) {
    this.publisher = publisher;
  }

  public OfferedResourceView language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @Schema(description = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public OfferedResourceView license(String license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  @Schema(description = "")
  public String getLicense() {
    return license;
  }

  public void setLicense(String license) {
    this.license = license;
  }

  public OfferedResourceView version(Long version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(description = "")
  public Long getVersion() {
    return version;
  }

  public void setVersion(Long version) {
    this.version = version;
  }

  public OfferedResourceView sovereign(String sovereign) {
    this.sovereign = sovereign;
    return this;
  }

   /**
   * Get sovereign
   * @return sovereign
  **/
  @Schema(description = "")
  public String getSovereign() {
    return sovereign;
  }

  public void setSovereign(String sovereign) {
    this.sovereign = sovereign;
  }

  public OfferedResourceView endpointDocumentation(String endpointDocumentation) {
    this.endpointDocumentation = endpointDocumentation;
    return this;
  }

   /**
   * Get endpointDocumentation
   * @return endpointDocumentation
  **/
  @Schema(description = "")
  public String getEndpointDocumentation() {
    return endpointDocumentation;
  }

  public void setEndpointDocumentation(String endpointDocumentation) {
    this.endpointDocumentation = endpointDocumentation;
  }

  public OfferedResourceView paymentModality(PaymentModalityEnum paymentModality) {
    this.paymentModality = paymentModality;
    return this;
  }

   /**
   * Get paymentModality
   * @return paymentModality
  **/
  @Schema(description = "")
  public PaymentModalityEnum getPaymentModality() {
    return paymentModality;
  }

  public void setPaymentModality(PaymentModalityEnum paymentModality) {
    this.paymentModality = paymentModality;
  }

  public OfferedResourceView samples(List<String> samples) {
    this.samples = samples;
    return this;
  }

  public OfferedResourceView addSamplesItem(String samplesItem) {
    if (this.samples == null) {
      this.samples = new ArrayList<>();
    }
    this.samples.add(samplesItem);
    return this;
  }

   /**
   * Get samples
   * @return samples
  **/
  @Schema(description = "")
  public List<String> getSamples() {
    return samples;
  }

  public void setSamples(List<String> samples) {
    this.samples = samples;
  }

  public OfferedResourceView additional(Map<String, String> additional) {
    this.additional = additional;
    return this;
  }

  public OfferedResourceView putAdditionalItem(String key, String additionalItem) {
    if (this.additional == null) {
      this.additional = new HashMap<>();
    }
    this.additional.put(key, additionalItem);
    return this;
  }

   /**
   * Get additional
   * @return additional
  **/
  @Schema(description = "")
  public Map<String, String> getAdditional() {
    return additional;
  }

  public void setAdditional(Map<String, String> additional) {
    this.additional = additional;
  }

  public OfferedResourceView _links(Links _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public Links getLinks() {
    return _links;
  }

  public void setLinks(Links _links) {
    this._links = _links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferedResourceView offeredResourceView = (OfferedResourceView) o;
    return Objects.equals(this.creationDate, offeredResourceView.creationDate) &&
        Objects.equals(this.modificationDate, offeredResourceView.modificationDate) &&
        Objects.equals(this.title, offeredResourceView.title) &&
        Objects.equals(this.description, offeredResourceView.description) &&
        Objects.equals(this.keywords, offeredResourceView.keywords) &&
        Objects.equals(this.publisher, offeredResourceView.publisher) &&
        Objects.equals(this.language, offeredResourceView.language) &&
        Objects.equals(this.license, offeredResourceView.license) &&
        Objects.equals(this.version, offeredResourceView.version) &&
        Objects.equals(this.sovereign, offeredResourceView.sovereign) &&
        Objects.equals(this.endpointDocumentation, offeredResourceView.endpointDocumentation) &&
        Objects.equals(this.paymentModality, offeredResourceView.paymentModality) &&
        Objects.equals(this.samples, offeredResourceView.samples) &&
        Objects.equals(this.additional, offeredResourceView.additional) &&
        Objects.equals(this._links, offeredResourceView._links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, modificationDate, title, description, keywords, publisher, language, license, version, sovereign, endpointDocumentation, paymentModality, samples, additional, _links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferedResourceView {\n");
    
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    modificationDate: ").append(toIndentedString(modificationDate)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    publisher: ").append(toIndentedString(publisher)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    sovereign: ").append(toIndentedString(sovereign)).append("\n");
    sb.append("    endpointDocumentation: ").append(toIndentedString(endpointDocumentation)).append("\n");
    sb.append("    paymentModality: ").append(toIndentedString(paymentModality)).append("\n");
    sb.append("    samples: ").append(toIndentedString(samples)).append("\n");
    sb.append("    additional: ").append(toIndentedString(additional)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
