/*
 * Dataspace Connector
 * IDS Connector originally developed by the Fraunhofer ISST
 *
 * OpenAPI spec version: 6.2.0
 * Contact: info@dataspace-connector.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.catenax.semantics.framework.dsc.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * PagedModelBrokerViewEmbedded
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-08T16:15:16.333286600+02:00[Europe/Berlin]")
public class PagedModelBrokerViewEmbedded {
  @JsonProperty("brokers")
  private List<BrokerView> brokers = null;

  public PagedModelBrokerViewEmbedded brokers(List<BrokerView> brokers) {
    this.brokers = brokers;
    return this;
  }

  public PagedModelBrokerViewEmbedded addBrokersItem(BrokerView brokersItem) {
    if (this.brokers == null) {
      this.brokers = new ArrayList<>();
    }
    this.brokers.add(brokersItem);
    return this;
  }

   /**
   * Get brokers
   * @return brokers
  **/
  @Schema(description = "")
  public List<BrokerView> getBrokers() {
    return brokers;
  }

  public void setBrokers(List<BrokerView> brokers) {
    this.brokers = brokers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagedModelBrokerViewEmbedded pagedModelBrokerViewEmbedded = (PagedModelBrokerViewEmbedded) o;
    return Objects.equals(this.brokers, pagedModelBrokerViewEmbedded.brokers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(brokers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagedModelBrokerViewEmbedded {\n");
    
    sb.append("    brokers: ").append(toIndentedString(brokers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
