/*
 * Dataspace Connector
 * IDS Connector originally developed by the Fraunhofer ISST
 *
 * OpenAPI spec version: 6.2.0
 * Contact: info@dataspace-connector.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.catenax.semantics.framework.dsc.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * PagedModelSubscriptionViewEmbedded
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-08T16:15:16.333286600+02:00[Europe/Berlin]")
public class PagedModelSubscriptionViewEmbedded {
  @JsonProperty("subscriptions")
  private List<SubscriptionView> subscriptions = null;

  public PagedModelSubscriptionViewEmbedded subscriptions(List<SubscriptionView> subscriptions) {
    this.subscriptions = subscriptions;
    return this;
  }

  public PagedModelSubscriptionViewEmbedded addSubscriptionsItem(SubscriptionView subscriptionsItem) {
    if (this.subscriptions == null) {
      this.subscriptions = new ArrayList<>();
    }
    this.subscriptions.add(subscriptionsItem);
    return this;
  }

   /**
   * Get subscriptions
   * @return subscriptions
  **/
  @Schema(description = "")
  public List<SubscriptionView> getSubscriptions() {
    return subscriptions;
  }

  public void setSubscriptions(List<SubscriptionView> subscriptions) {
    this.subscriptions = subscriptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagedModelSubscriptionViewEmbedded pagedModelSubscriptionViewEmbedded = (PagedModelSubscriptionViewEmbedded) o;
    return Objects.equals(this.subscriptions, pagedModelSubscriptionViewEmbedded.subscriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subscriptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagedModelSubscriptionViewEmbedded {\n");
    
    sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
