/*
 * Dataspace Connector
 * IDS Connector originally developed by the Fraunhofer ISST
 *
 * OpenAPI spec version: 6.2.0
 * Contact: info@dataspace-connector.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.catenax.semantics.framework.dsc.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * PagedModelObjectEmbedded
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-08T16:15:16.333286600+02:00[Europe/Berlin]")
public class PagedModelObjectEmbedded {
  @JsonProperty("objectList")
  private List<Object> objectList = null;

  public PagedModelObjectEmbedded objectList(List<Object> objectList) {
    this.objectList = objectList;
    return this;
  }

  public PagedModelObjectEmbedded addObjectListItem(Object objectListItem) {
    if (this.objectList == null) {
      this.objectList = new ArrayList<>();
    }
    this.objectList.add(objectListItem);
    return this;
  }

   /**
   * Get objectList
   * @return objectList
  **/
  @Schema(description = "")
  public List<Object> getObjectList() {
    return objectList;
  }

  public void setObjectList(List<Object> objectList) {
    this.objectList = objectList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagedModelObjectEmbedded pagedModelObjectEmbedded = (PagedModelObjectEmbedded) o;
    return Objects.equals(this.objectList, pagedModelObjectEmbedded.objectList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagedModelObjectEmbedded {\n");
    
    sb.append("    objectList: ").append(toIndentedString(objectList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
