/*
 * Dataspace Connector
 * IDS Connector originally developed by the Fraunhofer ISST
 *
 * OpenAPI spec version: 6.2.0
 * Contact: info@dataspace-connector.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.catenax.semantics.framework.dsc.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * PagedModelDataSourceViewEmbedded
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-08T16:15:16.333286600+02:00[Europe/Berlin]")
public class PagedModelDataSourceViewEmbedded {
  @JsonProperty("datasources")
  private List<DataSourceView> datasources = null;

  public PagedModelDataSourceViewEmbedded datasources(List<DataSourceView> datasources) {
    this.datasources = datasources;
    return this;
  }

  public PagedModelDataSourceViewEmbedded addDatasourcesItem(DataSourceView datasourcesItem) {
    if (this.datasources == null) {
      this.datasources = new ArrayList<>();
    }
    this.datasources.add(datasourcesItem);
    return this;
  }

   /**
   * Get datasources
   * @return datasources
  **/
  @Schema(description = "")
  public List<DataSourceView> getDatasources() {
    return datasources;
  }

  public void setDatasources(List<DataSourceView> datasources) {
    this.datasources = datasources;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagedModelDataSourceViewEmbedded pagedModelDataSourceViewEmbedded = (PagedModelDataSourceViewEmbedded) o;
    return Objects.equals(this.datasources, pagedModelDataSourceViewEmbedded.datasources);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datasources);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagedModelDataSourceViewEmbedded {\n");
    
    sb.append("    datasources: ").append(toIndentedString(datasources)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
