/*
 * Dataspace Connector
 * IDS Connector originally developed by the Fraunhofer ISST
 *
 * OpenAPI spec version: 6.2.0
 * Contact: info@dataspace-connector.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.catenax.semantics.framework.dsc.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * PagedModelRepresentationViewEmbedded
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-08T16:15:16.333286600+02:00[Europe/Berlin]")
public class PagedModelRepresentationViewEmbedded {
  @JsonProperty("representations")
  private List<RepresentationView> representations = null;

  public PagedModelRepresentationViewEmbedded representations(List<RepresentationView> representations) {
    this.representations = representations;
    return this;
  }

  public PagedModelRepresentationViewEmbedded addRepresentationsItem(RepresentationView representationsItem) {
    if (this.representations == null) {
      this.representations = new ArrayList<>();
    }
    this.representations.add(representationsItem);
    return this;
  }

   /**
   * Get representations
   * @return representations
  **/
  @Schema(description = "")
  public List<RepresentationView> getRepresentations() {
    return representations;
  }

  public void setRepresentations(List<RepresentationView> representations) {
    this.representations = representations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PagedModelRepresentationViewEmbedded pagedModelRepresentationViewEmbedded = (PagedModelRepresentationViewEmbedded) o;
    return Objects.equals(this.representations, pagedModelRepresentationViewEmbedded.representations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(representations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PagedModelRepresentationViewEmbedded {\n");
    
    sb.append("    representations: ").append(toIndentedString(representations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
