/*
 * Dataspace Connector
 * IDS Connector originally developed by the Fraunhofer ISST
 *
 * OpenAPI spec version: 6.2.0
 * Contact: info@dataspace-connector.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.catenax.semantics.framework.dsc.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;

/**
 * Permission
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-08T16:15:16.333286600+02:00[Europe/Berlin]")@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_atType", visible = true )
@JsonSubTypes({
})

public class Permission extends Rule {
  @JsonProperty("ids:postDuty")
  private List<Duty> idspostDuty = null;

  @JsonProperty("ids:preDuty")
  private List<Duty> idspreDuty = null;

  @JsonProperty("@type")
  private String _atType = null;

  public Permission idspostDuty(List<Duty> idspostDuty) {
    this.idspostDuty = idspostDuty;
    return this;
  }

  public Permission addIdspostDutyItem(Duty idspostDutyItem) {
    if (this.idspostDuty == null) {
      this.idspostDuty = new ArrayList<>();
    }
    this.idspostDuty.add(idspostDutyItem);
    return this;
  }

   /**
   * Get idspostDuty
   * @return idspostDuty
  **/
  @Schema(description = "")
  public List<Duty> getIdspostDuty() {
    return idspostDuty;
  }

  public void setIdspostDuty(List<Duty> idspostDuty) {
    this.idspostDuty = idspostDuty;
  }

  public Permission idspreDuty(List<Duty> idspreDuty) {
    this.idspreDuty = idspreDuty;
    return this;
  }

  public Permission addIdspreDutyItem(Duty idspreDutyItem) {
    if (this.idspreDuty == null) {
      this.idspreDuty = new ArrayList<>();
    }
    this.idspreDuty.add(idspreDutyItem);
    return this;
  }

   /**
   * Get idspreDuty
   * @return idspreDuty
  **/
  @Schema(description = "")
  public List<Duty> getIdspreDuty() {
    return idspreDuty;
  }

  public void setIdspreDuty(List<Duty> idspreDuty) {
    this.idspreDuty = idspreDuty;
  }

  public Permission _atType(String _atType) {
    this._atType = _atType;
    return this;
  }

   /**
   * Get _atType
   * @return _atType
  **/
  @Schema(required = true, description = "")
  public String getAtType() {
    return _atType;
  }

  public void setAtType(String _atType) {
    this._atType = _atType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Permission permission = (Permission) o;
    return Objects.equals(this.idspostDuty, permission.idspostDuty) &&
        Objects.equals(this.idspreDuty, permission.idspreDuty) &&
        Objects.equals(this._atType, permission._atType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idspostDuty, idspreDuty, _atType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Permission {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    idspostDuty: ").append(toIndentedString(idspostDuty)).append("\n");
    sb.append("    idspreDuty: ").append(toIndentedString(idspreDuty)).append("\n");
    sb.append("    _atType: ").append(toIndentedString(_atType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
