/*
 * Dataspace Connector
 * IDS Connector originally developed by the Fraunhofer ISST
 *
 * OpenAPI spec version: 6.2.0
 * Contact: info@dataspace-connector.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.catenax.semantics.framework.dsc.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * The subscription object.
 */
@Schema(description = "The subscription object.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-08T16:15:16.333286600+02:00[Europe/Berlin]")
public class SubscriptionDesc {
  @JsonProperty("title")
  private String title = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("target")
  private String target = null;

  @JsonProperty("location")
  private String location = null;

  @JsonProperty("subscriber")
  private String subscriber = null;

  @JsonProperty("pushData")
  private Boolean pushData = null;

  @JsonProperty("idsProtocol")
  private Boolean idsProtocol = null;

  public SubscriptionDesc title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public SubscriptionDesc description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SubscriptionDesc target(String target) {
    this.target = target;
    return this;
  }

   /**
   * Get target
   * @return target
  **/
  @Schema(description = "")
  public String getTarget() {
    return target;
  }

  public void setTarget(String target) {
    this.target = target;
  }

  public SubscriptionDesc location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @Schema(description = "")
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public SubscriptionDesc subscriber(String subscriber) {
    this.subscriber = subscriber;
    return this;
  }

   /**
   * Get subscriber
   * @return subscriber
  **/
  @Schema(description = "")
  public String getSubscriber() {
    return subscriber;
  }

  public void setSubscriber(String subscriber) {
    this.subscriber = subscriber;
  }

  public SubscriptionDesc pushData(Boolean pushData) {
    this.pushData = pushData;
    return this;
  }

   /**
   * Get pushData
   * @return pushData
  **/
  @Schema(description = "")
  public Boolean isPushData() {
    return pushData;
  }

  public void setPushData(Boolean pushData) {
    this.pushData = pushData;
  }

   /**
   * Get idsProtocol
   * @return idsProtocol
  **/
  @Schema(description = "")
  public Boolean isIdsProtocol() {
    return idsProtocol;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionDesc subscriptionDesc = (SubscriptionDesc) o;
    return Objects.equals(this.title, subscriptionDesc.title) &&
        Objects.equals(this.description, subscriptionDesc.description) &&
        Objects.equals(this.target, subscriptionDesc.target) &&
        Objects.equals(this.location, subscriptionDesc.location) &&
        Objects.equals(this.subscriber, subscriptionDesc.subscriber) &&
        Objects.equals(this.pushData, subscriptionDesc.pushData) &&
        Objects.equals(this.idsProtocol, subscriptionDesc.idsProtocol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, description, target, location, subscriber, pushData, idsProtocol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionDesc {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    target: ").append(toIndentedString(target)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    subscriber: ").append(toIndentedString(subscriber)).append("\n");
    sb.append("    pushData: ").append(toIndentedString(pushData)).append("\n");
    sb.append("    idsProtocol: ").append(toIndentedString(idsProtocol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
