/*
 * Dataspace Connector
 * IDS Connector originally developed by the Fraunhofer ISST
 *
 * OpenAPI spec version: 6.2.0
 * Contact: info@dataspace-connector.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.catenax.semantics.framework.dsc.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TypedLiteral
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-09-08T16:15:16.333286600+02:00[Europe/Berlin]")
public class TypedLiteral {
  @JsonProperty("@value")
  private String _atValue = null;

  @JsonProperty("@type")
  private String _atType = null;

  @JsonProperty("@language")
  private String _atLanguage = null;

  public TypedLiteral _atValue(String _atValue) {
    this._atValue = _atValue;
    return this;
  }

   /**
   * Get _atValue
   * @return _atValue
  **/
  @Schema(description = "")
  public String getAtValue() {
    return _atValue;
  }

  public void setAtValue(String _atValue) {
    this._atValue = _atValue;
  }

  public TypedLiteral _atType(String _atType) {
    this._atType = _atType;
    return this;
  }

   /**
   * Get _atType
   * @return _atType
  **/
  @Schema(description = "")
  public String getAtType() {
    return _atType;
  }

  public void setAtType(String _atType) {
    this._atType = _atType;
  }

  public TypedLiteral _atLanguage(String _atLanguage) {
    this._atLanguage = _atLanguage;
    return this;
  }

   /**
   * Get _atLanguage
   * @return _atLanguage
  **/
  @Schema(description = "")
  public String getAtLanguage() {
    return _atLanguage;
  }

  public void setAtLanguage(String _atLanguage) {
    this._atLanguage = _atLanguage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypedLiteral typedLiteral = (TypedLiteral) o;
    return Objects.equals(this._atValue, typedLiteral._atValue) &&
        Objects.equals(this._atType, typedLiteral._atType) &&
        Objects.equals(this._atLanguage, typedLiteral._atLanguage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_atValue, _atType, _atLanguage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypedLiteral {\n");
    
    sb.append("    _atValue: ").append(toIndentedString(_atValue)).append("\n");
    sb.append("    _atType: ").append(toIndentedString(_atType)).append("\n");
    sb.append("    _atLanguage: ").append(toIndentedString(_atLanguage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
