environment="int"
resource_group_name="catenax-int-rg"
image_registry="catenaxintacr.azurecr.io"
ingress_host="catenaxintakssrv.germanywestcentral.cloudapp.azure.com"
ingress_class_name="service"
aks_cluster_name="catenax-int-aks-services"
