apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clearinghouse-documents-api.fullname" . }}
  labels:
    {{- include "clearinghouse-documents-api.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env.config }}
    {{ $key }}: "{{ $val }}"
  {{- end}}
  {{- if index .Values "clearinghouse-documents-api-mongodb" "deploy" }}
    ROCKET_DATABASE_URL: "mongodb://{{ .Release.Name }}-clearinghouse-documents-api-mongodb:27017"
  {{- else }}
    ROCKET_DATABASE_URL: {{ index .Values "clearinghouse-documents-api-mongodb" "address" }}
  {{- end }}
  {{- if .Values.keyring_api.deploy }}
    ROCKET_KEYRING_API_URL: "http://{{ .Release.Name }}-clearinghouse-keyring-api:8002"
  {{- else }}
    ROCKET_KEYRING_API_URL: {{ .Values.keyring_api.address }}
  {{- end }}
