apiVersion: v1
kind: Secret
metadata:
  name: prs-connector-consumer-certificate
type: Opaque
data:
  # Roundtrip encode to base64 to verify the input is valid Base64.
  cert.pfx: {{ .Values.identity.certificateBase64 | b64dec | b64enc | quote }}
