apiVersion: v1
kind: Service
metadata:
  name: {{ include "vocab-core.fullname" . }}
  labels:
    {{- include "vocab-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: core-http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: core-vocol
      port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    {{- include "vocab-core.selectorLabels" . | nindent 4 }}
