# Default values for clearinghouse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets:
- name: regcred
nameOverride: ""
fullnameOverride: ""

ids:
  connector:
    image:
      repository: fraunhoferaisec/trusted-connector-core
      pullPolicy: Always
      tag: latest
  api:
    image:
      repository: catenaxdev001acr.azurecr.io/ids-clearing-house-api
      pullPolicy: Always
      tag: latest
    
  processor:
    jar:
      link: https://github.com/Fraunhofer-AISEC/ids-clearing-house-service/releases/download/v0.7.0/clearing-house-processors-1.1-SNAPSHOT.jar
      filename: clearing-house-processors-1.1-SNAPSHOT.jar
    xml:
      link: https://github.com/Fraunhofer-AISEC/ids-clearing-house-service/raw/v0.7.0/clearing-house-processors/src/routes/clearing-house-routes.xml
      filename: clearing-house-routes.xml

truststore:
  secretName: le-prod-truststore
  secretKey: truststore.p12

clearinghouse-documents-api:
  deploy: true
  address: "documents:8002"

clearinghouse-keyring-api:
  deploy: true
  address: "keyring:8002"

clearinghouse-api-mongo:
  deploy: true
  address: ""
  auth:
    enabled: false

env:
  config:
    RUST_BACKTRACE: "1"
    API_LOG_LEVEL: "Debug"
    ROCKET_CLEAR_DB: "true"
    ROCKET_DAPS_API_URL: "https://catenaxdev001akssrv.germanywestcentral.cloudapp.azure.com/daps"
    ROCKET_DATABASE_URL: "mongodb://{{ .Release.Name }}-clearinghouse-api-mongo:27017"

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/{{ .Release.Namespace }}/{{ .Release.Name }}"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: catenaxdev001akssrv.germanywestcentral.cloudapp.azure.com
      paths:
        - path: /{{ .Release.Namespace }}/{{ .Release.Name }}(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: daps-omejdn-server-tls
      hosts:
        - catenaxdev001akssrv.germanywestcentral.cloudapp.azure.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
