apiVersion: apps/v1
kind: Deployment
metadata:
  name: businesspartners
  namespace: businesspartners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: businesspartners
  template:
    metadata:
      labels:
        app: businesspartners
    spec:
      containers:
      - name: businesspartners
        image: $CONTAINER_REGISTRY/businesspartners:$VERSION
        imagePullPolicy: $IMAGE_PULL_POLICY
        env:
          - name: TABLENAME
            value: "BusinessPartners"
          - name: STORAGE_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                key: storage_connectionstring
                name: businesspartners-secret
          - name: HTTPUSERNAME
            value: "TractusX"
          - name: HTTPPASSWORD
            valueFrom:
              secretKeyRef:
                key: http_basic_auth_password
                name: businesspartners-secret
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: businesspartners
  namespace: businesspartners
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: businesspartners