apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdns
  namespace: cdns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdns
  template:
    metadata:
      labels:
        app: cdns
    spec:
      containers:
      - name: cdns
        image: $CONTAINER_REGISTRY/cdns:$VERSION
        imagePullPolicy: $IMAGE_PULL_POLICY
        ports:
        env:
          - name: MAPPINGTABLENAME
            value: "OneIdDnsMapping"
          - name: STORAGE_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                key: storage_connectionstring
                name: cdns-secret
          - name: HTTPUSERNAME
            value: "TractusX"
          - name: HTTPPASSWORD
            valueFrom:
              secretKeyRef:
                key: http_basic_auth_password
                name: cdns-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cdns
  namespace: cdns
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: cdns