#
# Copyright (c) 2021 T-Systems International GmbH (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

# K8 portal deployment, service and ingress 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  namespace: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
      - name: portal
        image: "catenaxacr.azurecr.io/frontend/portal:latest"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: portal
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: portal
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-ingress
  namespace: portal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-portal
    acme.cert-manager.io/http01-ingress-class: portal
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "false"
spec:
  ingressClassName: portal
  tls:
  - hosts:
    - ${CATENA_PORTAL_URL}
    secretName: certificate-secret
  rules:
  - host: ${CATENA_PORTAL_URL}
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: portal
            port:
              number: 80
  