# Copyright (c) 2022 Robert Bosch Manufacturing Solutions GmbH
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

###########################################################
# Configuration of the Semantic Layer
##########################################################
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
