apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clearinghouse-keyring-api.fullname" . }}
  labels:
    {{- include "clearinghouse-keyring-api.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.env.config }}
  {{ $key }}: "{{ $val }}"
{{- end}}
  {{- if index .Values "clearinghouse-keyring-api-mongodb" "deploy" }}
  ROCKET_DATABASE_URL: "mongodb://{{ .Release.Name }}-clearinghouse-keyring-api-mongodb:27017"
  {{- else }}
  ROCKET_DATABASE_URL: {{ index .Values "clearinghouse-keyring-api-mongodb" "address" }}
  {{- end }}
  default_doc_type.json: |
    {
      "id": "IDS_MESSAGE",
      "pid": "default",
      "parts": [
        {
          "name": "model_version"
        },
        {
          "name": "correlation_message"
        },
        {
          "name": "transfer_contract"
        },
        {
          "name": "issued"
        },
        {
          "name": "issuer_connector"
        },
        {
          "name": "content_version"
        },
        {
          "name": "recipient_connector"
        },
        {
          "name": "sender_agent"
        },
        {
          "name": "recipient_agent"
        },
        {
          "name": "payload"
        },
        {
          "name": "payload_type"
        },
        {
          "name": "message_id"
        }
      ]
    }
