apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metadata-broker-open-core.fullname" . }}
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
  {{- if .Values.broker.truststore.p12 }}
  truststore: {{ .Values.broker.truststore.p12 | b64enc }}
  truststore_password: {{ .Values.broker.truststore.password | b64enc }}
  {{- end }}
{{- ( include "gen.secret" . ) | indent 2 -}}