#
# Copyright (c) 2021 Microsoft (Catena-X Consortium)
#
# See the AUTHORS file(s) distributed with this work for additional
# information regarding authorship.
#
# See the LICENSE file(s) distributed with this work for
# additional information regarding license terms.
#

#################################################################################################################
# Github Workflow for continuous deployment of the test data generator to non-production environments 
#################################################################################################################
# The following secrets are expected to be set
# AZURE_CREDENTIALS           - JSON object containing all info to login to azure via a Service Principal (SP)
#################################################################################################################
# If you intend to use the test data generator in new branches/workspaces/landscapes, see the comments marked 
# ADAPT HERE TO ADD NEW WORKSPACES

name: SwaggerService

on: 
  push:
    paths:
      # This is where the swagger service related sources reside
      - 'data/portal-td-stub/**'
      # this workflow file
      - '.github/workflows/swagger-service.yml'
    
env:
  prefix: catenax

jobs:
  ########################################
  # First job to determine the environment
  ########################################
  # ADAPT HERE TO ADD NEW WORKSPACES

  environment:
    name: Determine Target Environment
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ steps.setvars.outputs.workspace }}

    steps:
      - name: Set variables
        id: setvars
        run: |
            if [[ "${{github.repository}}" == tractusx-team-portal-onboarding/tractusx ]]; then
              if [[ "${{github.ref}}" == refs/heads/main ]]; then
                echo "Determined INTEGRATION"
                echo "::set-output name=workspace::int"
              else 
                echo "Set workspace to DEVELOPMENT. Defaults to landscape dev003 for DB settings."
                echo "::set-output name=workspace::dev003"
              fi
            else
                echo "Unsupported Repository. Leaving Workspace empty."
            fi

  #########################################################################################
  # Second job does the deployment of the test data generator to the determined environment
  #########################################################################################
  
  deploy:
    name: Deploy Swagger Service
    runs-on: ubuntu-latest
    # rely on the first job
    needs: environment
    # rely on successful detection of the workspace, ignore if empty
    if: ${{needs.environment.outputs.workspace}}
    env:
      WORKSPACE: ${{needs.environment.outputs.workspace}}
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Get Swagger Service DB - only applicable in non-prod environments
      - name: Azure Try Existing Test Data Generator DB in non-prod environments
        if: |
          ${{needs.environment.outputs.workspace}} != "prod"
        continue-on-error: true
        id: try_swaggerservice_db
        run: |
          echo "::set-output name=SWAGGERSERVICEDB::$(az postgres db list --resource-group ${{env.prefix}}-${{needs.environment.outputs.workspace}}-rg --server-name ${{env.prefix}}${{needs.environment.outputs.workspace}}database --output json | jq -r '.[] | select(.name=="portal") | .id')"
      
      # Create Swagger Service DB If needed in non-prod environments
      - name: Azure Create Swagger Service DB
        if: |
          ${{needs.environment.outputs.workspace}} != "prod" && ${{steps.try_swaggerservice_db.outputs.SWAGGERSERVICEDB == '' }}        
        run: |
          az postgres db create --name "portal" --resource-group ${{env.prefix}}-${{needs.environment.outputs.workspace}}-rg --server-name ${{env.prefix}}${{needs.environment.outputs.workspace}}database

      # Substitute placeholders in application properties file before build
      - name: Configure application properties
        working-directory: ./data/portal-td-stub/src/main/resources
        env: 
          # SERVER_HOST: swaggerservicedev.germanywestcentral.azurecontainer.io
          SERVER_PORT: 8080
          DB_USER: CatenaX@catenax${{needs.environment.outputs.workspace}}database
          DB_PWD: ${{ secrets.CATENAX_PASSWORD }}
          DB_HOST_FQDN: catenax${{needs.environment.outputs.workspace}}database.postgres.database.azure.com
          DB_HOST: catenax${{needs.environment.outputs.workspace}}database
          DB_PORT: 5432
          DB_NAME: portal
          DB_SCHEMA: public
        run: |
          envsubst < application.yml > application.yml.tmp
          rm application.yml
          mv application.yml.tmp application.yml
          cat application.yml
     
      - name: Build with Maven
        working-directory: ./data/portal-td-stub
        run: |
          mvn clean package -DskipTests
        
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: catenaxacr.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push docker image for swagger service
        working-directory: ./data/portal-td-stub
        run: |
          docker build -f src/main/docker/Dockerfile -t catenaxacr.azurecr.io/tractusx/swaggerservice${{needs.environment.outputs.workspace}}:${{ github.run_id }} .
          docker push catenaxacr.azurecr.io/tractusx/swaggerservice${{needs.environment.outputs.workspace}}:${{ github.run_id }}

      - name: Deploy swagger service to Azure Container Instances
        run: |
          az container create --resource-group shared-services-rg --name swaggerservicedev --image catenaxacr.azurecr.io/tractusx/swaggerservice${{needs.environment.outputs.workspace}}:${{ github.run_id }} --restart-policy OnFailure --ports 8080 --dns-name-label swaggerservicedev --registry-password ${{ secrets.AZURE_REGISTRY_PASSWORD }} --registry-username ${{ secrets.AZURE_REGISTRY_USERNAME }} --cpu 2 --memory 3.5
